var charData = {
    "Curlew Kai": "biaoyu_g",
    "Fiji_2": "feiji_2",
    "Curacoa Kai": "kulasuo_g",
    "Southampton": "nananpudun",
    "Swiftsure": "quejie",
    "Swiftsure_2": "quejie_2",
    "Sirius_3": "tianlangxing_3",
    "Matchless_2": "wudi_2",
    "Chaser_3": "zhuiganzhe_3",
    
    "Z1 Kai": "z1_g",
    "Leipzig Kai": "laibixi_g",
    
    "Bismarck_2": "bisimai_2",
    "Hornet_2": "dahuangfeng_2",
    "Little Helena": "hailunna_younv",
    "Helena_3": "hailunna_3",
    "Ark Royal_3": "huangjiafangzhou_3",
    "Little Cleveland": "kelifulan_younv",
    "Little Sandy": "shengdiyage_younv",
    "Shigure_3": "shiyu_3",
    "Admiral Graf Spee_4": "sipeibojue_4",
    "Yuugure_4": "ximu_4",
    "Yorktown_2": "yuekecheng_2",
    "Z23_3": "z23_3",
    "Georgia_2": "zuozhiya_2",
    
    "San Francisco(?)": "aidahe",
    
    "Z36": "z36",
    "Koln Kai": "kelong_g",
    "U-556_2": "U556_2",
    "U-73": "U73",
    "U-73_3": "U73_3",
    "Echo": "huisheng",
    "King George V": "qiaozhiwushi",
    
    "Akashi_4": "mingshi_4",
    "U-556": "u556",
    
    "Bush_2": "bushi_2",
    "Hermes Kai": "jingjishen_g",
    "Memphis_2": "mengfeisi_2",
    
    "Ai_manjuu": "Ai_manjuu",
    "ai_manjuuu": "ai_manjuuu",
    "Kizuna AI (BB)": "aijiangBB",
    "Kizuna AI (CL)": "aijiangCL",
    "Kizuna AI (CV)": "aijiangCV",
    "Kizuna AI (DD)": "aijiangDD",
    "Kizuna AI (DD)_2": "aijiangDD_2",
    "Saratoga_4": "salatuojia_4",
    
    "Javelin_4": "biaoqiang_4",
    "Laffey_5": "lafei_5",
    "Ayanami_6": "lingbo_6",
    "Z23_4": "z23_4",
    
    "Kisaragi Kai": "ruyue_g",

    "An Shan_2": "anshan_2",
    
    "Hiei-chan": "birui_younv",
    "Akagi-chan": "chicheng_younv",
    "Zeppelin-chan": "qibolin_younv",
    
    "Kitakaze": "beifeng",
    "Friedrich der Grosse": "feiteliedadi",
    "Gascogne": "jiasikenie",
    "Azuma": "wuqi",
    "Seattle": "xiyatu",
    "Georgia": "zuozhiya",
    
    "Nagato_2": "changmen_2",
    "Illustrious_4": "guanghui_4",
    "I-13": "i13",
    "Kongou_2": "jingang_2",
    "Isuzu": "linggu",
    "Mutsu_2": "luao_2",
    "Saratoga_3": "salatuojia_3",
    "Yoizuki_2": "xiaoyue_2",

    "22": "22",
    "33": "33",
    "Abercrombie": "abeikelongbi",
    "Abukuma Kai": "awuwei_g",
    "Abukuma": "awuwei",
    "Acasta Kai": "akasita_g",
    "Acasta": "akasita",
    "Acasta_2": "akasita_2",
    "Achilles Kai": "ajilisi_g",
    "Achilles": "ajilisi",
    "Admiral Graf Spee": "sipeibojue",
    "Admiral Graf Spee_2": "sipeibojue_2",
    "Admiral Graf Spee_3": "sipeibojue_3",
    "Admiral Hipper": "xipeierhaijunshangjiang",
    "Agano": "aheye",
    "Ajax Kai": "ajiakesi_g",
    "Ajax": "ajiakesi",
    "Ajax_2": "ajiakesi_2",
    "Akagi Wedding": "chicheng_h",
    "Akagi": "chicheng",
    "Akagi_2": "chicheng_2",
    "Akagi_3": "chicheng_3",
    "Akashi": "mingshi",
    "Akashi_2": "mingshi_2",
    "Akashi_3": "mingshi_3",
    "Akatsuki": "xiao",
    "Akatsuki_2": "xiao_2",
    "Albacore": "daqinghuayu",
    "Amagi": "tiancheng",
    "Amazon": "nvjiang",
    "Amazon_2": "nvjiang_2",
    "An Shan": "anshan",
    "Aoba": "qingye",
    "Arashio": "huangchao",
    "Ardent Kai": "rexin_g",
    "Ardent": "rexin",
    "Arethusa": "aruituosha",
    "Ariake": "youming",
    "Arizona": "yalisangna",
    "Ark Royal": "huangjiafangzhou",
    "Ark Royal_2": "huangjiafangzhou_2",
    "Asashio": "zhaochao",
    "Asashio_2": "zhaochao_2",
    "Ashigara": "zubing",
    "Ashigara_2": "zubing_2",
    "Astoria": "asituoliya",
    "Astoria_3": "asituoliya_3",
    "Atago Wedding": "aidang_h",
    "Atago": "aidang",
    "Atago_2": "aidang_2",
    "Atago_3": "aidang_3",
    "Atago_4": "aidang_4",
    "Atlanta": "yatelanda",
    "Aulick": "aolike",
    "Aurora": "ouruola",
    "Aurora_2": "ouruola_2",
    "Aurora_3": "ouruola_3",
    "Avrora": "afuleer",
    "Ayanami Kai": "lingbo_g",
    "Ayanami Wedding": "lingbo_h",
    "Ayanami": "lingbo",
    "Ayanami_2": "lingbo_2",
    "Ayanami_3": "lingbo_3",
    "Ayanami_4": "lingbo_4",
    "Ayanami_5": "lingbo_5",
    "Bailey Kai": "beili_g",
    "Bailey": "beili",
    "Bailey_2": "beili_2",
    "Beagle": "xiaolietuquan",
    "Belchan": "beierfasite_younv",
    "Belfast Wedding": "beierfasite_h",
    "Belfast": "beierfasite",
    "Belfast_2": "beierfasite_2",
    "Benson": "bensen",
    "Bismarck": "bisimai",
    "Blanc (HDN)": "HDN301",
    "Bogue Kai": "boge_g",
    "Bogue": "boge",
    "Brooklyn": "bulukelin",
    "Bulldog": "dadouquan",
    "Bullin Skill": "gin_skill",
    "Bullin": "gin",
    "Bunker Hill": "bangkeshan",
    "Bush": "bushi",
    "California": "jialifuniya",
    "Cassin Kai": "kaxin_g",
    "Cassin": "kaxin",
    "Centaur": "banrenma",
    "Centaur_2": "banrenma_2",
    "Centaur_3": "banrenma_3",
    "Chang Chun": "changchun",
    "Chang Chun_2": "changchun_2",
    "Charles Ausburne": "aosiben",
    "Chaser": "zhuiganzhe",
    "Chaser_2": "zhuiganzhe_2",
    "Chicago": "zhijiage",
    "Chikuma": "zhumo",
    "Choukai": "niaohai",
    "Cleveland Wedding": "kelifulan_h",
    "Cleveland": "kelifulan",
    "Cleveland_2": "kelifulan_2",
    "Cleveland_3": "kelifulan_3",
    "Columbia": "gelunbiya",
    "Comet Kai": "huixing_g",
    "Comet": "huixing",
    "Concord": "kangkede",
    "Concord_2": "kangkede_2",
    "Craven": "keleiwen",
    "Craven_2": "keleiwen_2",
    "Crescent Kai": "xinyue_g",
    "Crescent": "xinyue",
    "Curacoa": "kulasuo",
    "Curacoa_2": "kulasuo_2",
    "Curlew": "biaoyu",
    "Curlew_2": "biaoyu_2",
    "Cygnet (The Offer is Maid)": "xiaotiane_4",
    "Cygnet Kai": "xiaotiane_g",
    "Cygnet": "xiaotiane",
    "Cygnet_2": "xiaotiane_2",
    "Cygnet_3": "xiaotiane_3",
    "Cygnet_5": "xiaotiane_5",
    "Dace": "tiaoyu",
    "Denver": "danfo",
    "Deutschland": "deyizhi",
    "Deutschland_2": "deyizhi_2",
    "Deutschland_3": "deyizhi_3",
    "Dewey": "duwei",
    "Dorsetshire": "duosaitejun",
    "Downes Kai": "tangsi_g",
    "Downes": "tangsi",
    "Duke of York": "yuekegongjue",
    "Duke of York_3": "yuekegongjue_3",
    "Dunkerque": "dunkeerke",
    "Dunkerque_2": "dunkeerke_2",
    "Edinburgh": "aidingbao",
    "Edinburgh_2": "aidingbao_2",
    "Eidsvold": "eidsvold",
    "Eldridge": "aierdeliqi",
    "Eldridge_2": "aierdeliqi_2",
    "Eldridge_3": "aierdeliqi_3",
    "Eldridge_4": "aierdeliqi_4",
    "Emile Bertin": "aimierbeierding",
    "Emile Bertin_2": "aimierbeierding_2",
    "Enterprise Wedding": "qiye_h",
    "Enterprise": "qiye",
    "Enterprise_2": "qiye_2",
    "Enterprise_3": "qiye_3",
    "Enterprise_dark": "qiye_dark",
    "Erebus": "heianjie",
    "Erebus_2": "heianjie_2",
    "Essex": "aisaikesi",
    "Exeter Kai": "aikesaite_g",
    "Exeter": "aikesaite",
    "Fiji": "feiji",
    "Fletcher": "fulaiche",
    "Foote": "fute",
    "Forbin Kai": "fuerban_g",
    "Forbin": "fuerban",
    "Forbin_2": "fuerban_2",
    "Fortune Kai": "mingyunnvshen_g",
    "Fortune": "mingyunnvshen",
    "Fortune_2": "mingyunnvshen_2",
    "Foxhound Kai": "huti_g",
    "Foxhound": "huti",
    "Fu Shun": "fushun",
    "Fubuki": "chuixue",
    "Fubuki_2": "chuixue_2",
    "Fubuki_3": "chuixue_3",
    "Fubuki_4": "chuixue_4",
    "Fumiruiru": "fumilulu",
    "Fumiruiru_2": "fumilulu_2",
    "Fumizuki": "wenyue",
    "Fumizuki_2": "wenyue_2",
    "Furutaka Kai": "guying_g",
    "Furutaka": "guying",
    "Fusou Kai": "fusang_g",
    "Fusou": "fusang",
    "Fusou_2": "fusang_2",
    "Fusou_3": "fusang_3",
    "Galatea": "jialadiya",
    "Glorious": "guangrong",
    "Glorious_2": "guangrong_2",
    "Glowworm": "yinghuochong",
    "Gneisenau": "genaisennao",
    "Graf Zeppelin": "qibolin",
    "Graf Zeppelin_2": "qibolin_2",
    "Grenville": "gelunweier",
    "Gridley": "gelideli",
    "Gridley_2": "gelideli_2",
    "HDN102_1": "HDN102_1",
    "HDN102_2": "HDN102_2",
    "HDN202_1": "HDN202_1",
    "HDN202_2": "HDN202_2",
    "HDN302_1": "HDN302_1",
    "HDN302_2": "HDN302_2",
    "HDN402_1": "HDN402_1",
    "HDN402_2": "HDN402_2",
    "Hamakaze Kai": "bangfeng_g",
    "Hamakaze": "bangfeng",
    "Hamakaze_2": "bangfeng_2",
    "Hammann Kai": "haman_g",
    "Hammann": "haman",
    "Hammann_2": "haman_2",
    "Hardy": "yonggan",
    "Haruna": "zhenming",
    "Haruna_2": "zhenming_2",
    "Harutsuki": "chunyue",
    "Hatakaze": "qifeng",
    "Hatsuharu": "chuchun",
    "Hatsuharu_2": "chuchun_2",
    "Hatsushimo": "chushuang",
    "Hazelwood": "heizewude",
    "Helena": "hailunna",
    "Helena_2": "hailunna_2",
    "Hermes": "jingjishen",
    "Hiei": "birui",
    "Hiei_2": "birui_2",
    "Hiryuu Kai": "feilong_g",
    "Hiryuu": "feilong",
    "Hiryuu_2": "feilong_2",
    "Hiyou": "feiying",
    "Hobby": "huobi",
    "Hobby_2": "huobi_2",
    "Honolulu": "huonululu",
    "Honolulu_2": "huonululu_2",
    "Honolulu_3": "huonululu_3",
    "Honolulu_4": "huonululu_4",
    "Hornet": "dahuangfeng",
    "Houshou": "fengxiang",
    "Houshou_2": "fengxiang_2",
    "Houston": "xiusidun",
    "Hunter": "lieren",
    "Hyuuga Kai": "rixiang_g",
    "Hyuuga": "rixiang",
    "I-19": "I19",
    "I-19_2": "I19_2",
    "I-26": "I26",
    "I-26_2": "I26_2",
    "I-58": "I58",
    "I-8": "I8",
    "Ibuki": "yichui",
    "Ibuki_2": "yichui_2",
    "Ikazuchi": "lei",
    "Ikazuchi_2": "lei_2",
    "Illustrious Wedding": "guanghui_h",
    "Illustrious": "guanghui",
    "Illustrious_2": "guanghui_2",
    "Illustrious_3": "guanghui_3",
    "Inazuma": "dian",
    "Inazuma_2": "dian_2",
    "Independence": "duli",
    "Independence_2": "duli_2",
    "Indianapolis": "bolisi",
    "Indianapolis_2": "bolisi_2",
    "Ise Kai": "yishi_g",
    "Ise": "yishi",
    "Isokaze": "jifeng",
    "Isokaze_2": "jifeng_2",
    "Isuzu": "wushiling",
    "Isuzu_2": "wushiling_2",
    "Izumo": "chuyun",
    "Izumo_2": "chuyun_2",
    "Jamaica": "yamaijia",
    "Jamaica_2": "yamaijia_2",
    "Javelin Kai": "biaoqiang_g",
    "Javelin Wedding": "biaoqiang_h",
    "Javelin": "biaoqiang",
    "Javelin_2": "biaoqiang_2",
    "Javelin_3": "biaoqiang_3",
    "Jean Bart": "rangbaer",
    "Jenkins": "jiejinsi",
    "Jersey": "zexi",
    "Jintsuu Kai": "shentong_g",
    "Jintsuu": "shentong",
    "Jintsuu_2": "shentong_2",
    "Juneau": "zhunuo",
    "Juno": "tianhou",
    "Junyou": "sunying",
    "Jupiter": "qiubite",
    "Kaga BB": "jiahezhanlie",
    "Kaga Wedding": "jiahe_h",
    "Kaga": "jiahe",
    "Kaga_2": "jiahe_2",
    "Kaga_3": "jiahe_3",
    "Kagerou Kai": "yangyan_g",
    "Kagerou": "yangyan",
    "Kagerou_2": "yangyan_2",
    "Kako Kai": "jiagu_g",
    "Kako": "jiagu",
    "Kalk": "keerke",
    "Kalk_2": "keerke_2",
    "Kamikaze Kai": "shenfeng_g",
    "Kamikaze": "shenfeng",
    "Karlsruhe Kai": "kaersilue_g",
    "Karlsruhe": "kaersilue",
    "Kawakaze": "jiangfeng",
    "Kawakaze_2": "jiangfeng_2",
    "Kent": "kente",
    "Kimberly": "jinboli",
    "Kimberly_3": "jinboli_3",
    "Kinugasa": "yili",
    "Kirishima": "wudao",
    "Kirishima_2": "wudao_2",
    "Kisaragi": "ruyue",
    "Kisaragi_2": "ruyue_2",
    "Koln": "kelong",
    "Kolorado (Old)": "keluoladuo_2",
    "Kolorado": "keluoladuo",
    "Kongou": "jingang",
    "Konigsberg": "kenisibao",
    "Kuon (UTA)": "jiuyuan",
    "Kuon (UTA)_2": "jiuyuan_2",
    "Kuroshio": "heichao",
    "Laffey Kai": "lafei_g",
    "Laffey": "lafei",
    "Laffey_2": "lafei_2",
    "Laffey_3": "lafei_3",
    "Laffey_4": "lafei_4",
    "Langley Kai": "lanli_g",
    "Langley": "lanli",
    "Le Mars Kai": "lemaer_g",
    "Le Mars": "lemaer",
    "Le Mars_2": "lemaer_2",
    "Le Temeraire": "lumang",
    "Le Triomphant": "kaixuan",
    "Leander Kai": "liande_g",
    "Leander": "liande",
    "Leipzig": "laibixi",
    "Lexington": "liekexingdun",
    "Lexington_2": "liekexingdun_2",
    "London": "lundun",
    "Long Island Kai": "changdao_g",
    "Long Island": "changdao",
    "Long Island_2": "changdao_2",
    "Makinami": "juanbo",
    "Maryland (Old)": "malilan_2",
    "Maryland": "malilan",
    "Massachusetts": "masazhusai",
    "Matchless": "wudi",
    "Matsukaze Kai": "songfeng_g",
    "Matsukaze": "songfeng",
    "Maury": "moli",
    "Maya": "moye",
    "McCall": "maikaoer",
    "Memphis": "mengfeisi",
    "Michishio": "manchao",
    "Mikasa": "sanli",
    "Mikasa_2": "sanli_2",
    "Mikasa_4": "sanli_4",
    "Mikazuki": "sanriyue",
    "Mikuma": "sanwei",
    "Minazuki": "shuiwuyue",
    "Minneapolis": "mingniabolisi",
    "Minneapolis_2": "mingniabolisi_2",
    "Mogami Kai": "zuishang_g",
    "Mogami": "zuishang",
    "Monarch": "junzhu",
    "Monarch_2": "junzhu_2",
    "Monarch_3": "junzhu_3",
    "Montpelier": "mengbiliai",
    "Montpelier_2": "mengbiliai_2",
    "Mullany": "malani",
    "Mullany_3": "malani_3",
    "Musketeer": "huoqiangshou",
    "Mutsu": "luao",
    "Mutsuki Kai": "muyue_g",
    "Mutsuki": "muyue",
    "Mutsuki_2": "muyue_2",
    "Myoukou": "miaogao",
    "Nachi": "nazhi",
    "Nagara": "changliang",
    "Nagato Wedding": "changmen_h",
    "Nagato": "changmen",
    "Nagatsuki": "changyue",
    "Naka": "nake",
    "NekoBox1": "NekoBox1",
    "NekoBox2": "NekoBox2",
    "NekoBox3": "NekoBox3",
    "NekoBox4": "NekoBox4",
    "Nekone (UTA)": "maoyin",
    "Nekone (UTA)_2": "maoyin_2",
    "Nelson": "naerxun",
    "Nelson_2": "naerxun_2",
    "Neptune (HDN)": "HDN101",
    "Neptune": "haiwangxing",
    "Nevada Kai": "neihuada_g",
    "Nevada": "neihuada",
    "Newcastle Kai": "niukasier_g",
    "Newcastle": "niukasier",
    "Newcastle_2": "niukasier_2",
    "Nicholas Kai": "nigulasi_g",
    "Nicholas": "nigulasi",
    "Nicholas_2": "nigulasi_2",
    "Nicholas_3": "nigulasi_3",
    "Niizuki": "xinyue_jp",
    "Ning Hai Kai": "ninghai_g",
    "Ning Hai": "ninghai",
    "Ning Hai_2": "ninghai_2",
    "Ning Hai_3": "ninghai_3",
    "Noire (HDN)": "HDN201",
    "Norfolk": "nuofuke",
    "North Carolina": "beikaluolaina",
    "Northampton": "beianpudun",
    "Nowaki": "yefen",
    "Oklahoma Kai": "ekelahema_g",
    "Oklahoma": "ekelahema",
    "Omaha": "aomaha",
    "Ooshio": "dachao",
    "Ooshio_2": "dachao_2",
    "Oyashio": "qinchao",
    "Pennsylvania": "binxifaniya",
    "Pensacola": "pengsakela",
    "Phoenix": "feinikesi",
    "Ping Hai Kai": "pinghai_g",
    "Ping Hai": "pinghai",
    "Ping Hai_2": "pinghai_2",
    "Ping Hai_3": "pinghai_3",
    "Portland Kai": "botelan_g",
    "Portland": "botelan",
    "Portland_2": "botelan_2",
    "Prince of Wales": "weiershiqinwang",
    "Prince of Wales_2": "weiershiqinwang_2",
    "Prince of Wales_4": "weiershiqinwang_4",
    "Prinz Eugen Wedding": "ougen_h",
    "Prinz Eugen": "ougen",
    "Prinz Eugen_2": "ougen_2",
    "Prinz Eugen_3": "ougen_3",
    "Queen Elizabeth": "yilishabai",
    "Queen Elizabeth_2": "yilishabai_2",
    "Quincy": "kunxi",
    "Quincy_2": "kunxi_2",
    "Radford": "ladefute",
    "Raleigh": "luoli",
    "Ranger Kai": "tujizhe_g",
    "Ranger": "tujizhe",
    "Renown": "shengwang",
    "Repulse": "fanji",
    "Richmond": "lishiman",
    "Rodney": "luodeni",
    "Rodney_2": "luodeni_2",
    "Rodney_3": "luodeni_3",
    "Roon": "luoen",
    "Rurutie (UTA)": "lulutiye",
    "Rurutie (UTA)_2": "lulutiye_2",
    "Ryuujou": "longxiang",
    "Ryuujou_2": "longxiang_2",
    "SRNekoBox1": "SRNekoBox1",
    "SRNekoBox2": "SRNekoBox2",
    "SRNekoBox3": "SRNekoBox3",
    "SRNekoBox4": "SRNekoBox4",
    "SSRNekoBox1": "SSRNekoBox1",
    "SSRNekoBox2": "SSRNekoBox2",
    "SSRNekoBox3": "SSRNekoBox3",
    "SSRNekoBox4": "SSRNekoBox4",
    "Saint Louis": "luyijiushi",
    "Salt Lake City": "yanhucheng",
    "San Diego Kai": "shengdiyage_g",
    "San Diego": "shengdiyage",
    "San Diego_2": "shengdiyage_2",
    "Saraana (UTA)": "salana",
    "Saraana (UTA)_2": "salana_2",
    "Saratoga Kai": "salatuojia_g",
    "Saratoga": "salatuojia",
    "Saratoga_2": "salatuojia_2",
    "Scharnhorst": "shaenhuosite",
    "Sendai Kai": "chuannei_g",
    "Sendai": "chuannei",
    "Shangri-La": "xianggelila",
    "Shangri-La_2": "xianggelila_2",
    "Sheffield": "xiefeierde",
    "Sheffield_2": "xiefeierde_2",
    "Shigure": "shiyu",
    "Shigure_2": "shiyu_2",
    "Shiranui Kai": "buzhihuo_g",
    "Shiranui": "buzhihuo",
    "Shiratsuyu": "bailu",
    "Shiratsuyu_2": "bailu_2",
    "Shouhou Kai": "xiangfeng_g",
    "Shouhou": "xiangfeng",
    "Shouhou_2": "xiangfeng_2",
    "Shoukaku": "xianghe",
    "Shropshire": "shiluopujun",
    "Sims Kai": "ximusi_g",
    "Sims": "ximusi",
    "Sirius": "tianlangxing",
    "Sirius_2": "tianlangxing_2",
    "Souryuu Kai": "canglong_g",
    "Souryuu": "canglong",
    "Souryuu_2": "canglong_2",
    "Souryuu_3": "canglong_3",
    "South Dakota": "nandaketa",
    "South Dakota_2": "nandaketa_2",
    "Spence": "sipengsi",
    "St. Louis": "shengluyisi",
    "St. Louis_2": "shengluyisi_2",
    "St. Louis_3": "shengluyisi_3",
    "Suffolk Kai": "safuke_g",
    "Suffolk": "safuke",
    "Surcouf": "xukufu",
    "Sussex": "susaikesi",
    "Tai Yuan": "taiyuan",
    "Tai Yuan_2": "taiyuan_2",
    "Taihou": "dafeng",
    "Taihou_2": "dafeng_2",
    "Takao Wedding": "gaoxiong_h",
    "Takao": "gaoxiong",
    "Takao_2": "gaoxiong_2",
    "Takao_3": "gaoxiong_3",
    "Takao_4": "gaoxiong_4",
    "Tanikaze Kai": "gufeng_g",
    "Tanikaze": "gufeng",
    "Tanikaze_2": "gufeng_2",
    "Tennessee": "tiannaxi",
    "Terror": "kongbu",
    "Terror_2": "kongbu_2",
    "Thatcher": "saqieer",
    "Tirpitz": "tierbici",
    "Tirpitz_2": "tierbici_2",
    "Tone": "ligen",
    "Trial Bullin MKII Skill": "kin_skill",
    "Trial Bullin MKII": "kin",
    "U-47": "U47",
    "U-47_2": "U47_2",
    "U-557": "U557",
    "U-81": "U81",
    "U-81_2": "U81_2",
    "Unicorn": "dujiaoshou",
    "Unicorn_2": "dujiaoshou_2",
    "Unicorn_3": "dujiaoshou_3",
    "Unicorn_4": "dujiaoshou_4",
    "Urakaze": "pufeng",
    "Urakaze_2": "pufeng_2",
    "Uruuru (UTA)": "wululu",
    "Uruuru (UTA)_2": "wululu_2",
    "Uzuki": "maoyue",
    "Uzuki_2": "maoyue_2",
    "Vampire Wedding": "xixuegui_h",
    "Vampire": "xixuegui",
    "Vampire_2": "xixuegui_2",
    "Vampire_3": "xixuegui_3",
    "Vert (HDN)": "HDN401",
    "Vestal": "zaoshen",
    "Vestal_2": "zaoshen_2",
    "Victorious": "shengli",
    "Victorious_2": "shengli_2",
    "Vincennes": "wensensi",
    "Vincennes_2": "wensensi_2",
    "Vincennes_3": "wensensi_3",
    "Wakaba": "ruoye",
    "Warspite Kai": "yanzhan_g",
    "Warspite": "yanzhan",
    "Warspite_2": "yanzhan_2",
    "Washington": "huashengdun",
    "Wasp": "hufeng",
    "West Virginia (Old)": "xifujiniya_2",
    "West Virginia": "xifujiniya",
    "Wichita": "weiqita",
    "Yamashiro Kai": "shancheng_g",
    "Yamashiro Wedding": "shancheng_h",
    "Yamashiro": "shancheng",
    "Yamashiro_2": "shancheng_2",
    "Yamashiro_3": "shancheng_3",
    "Yamashiro_4": "shancheng_4",
    "Yat Sen": "yixian",
    "Yoizuki": "xiaoyue",
    "York Kai": "yueke_g",
    "York": "yueke",
    "Yorktown": "yuekecheng",
    "Yukikaze (Spring's Warmth)": "xuefeng_h",
    "Yukikaze (Swings-Sama)": "xuefeng_2",
    "Yukikaze": "xuefeng",
    "Yuubari": "xizhang",
    "Yuubari Kai": "xizhang_g",
    "Yuudachi Wedding": "xili_h",
    "Yuudachi": "xili",
    "Yuudachi_2": "xili_2",
    "Yuudachi_3": "xili_3",
    "Yuugure": "ximu",
    "Yuugure_2": "ximu_2",
    "Yuugure_3": "ximu_3",
    "Z1": "z1",
    "Z18": "z18",
    "Z19": "Z19",
    "Z1_2": "Z1_2",
    "Z2": "z2",
    "Z20": "z20",
    "Z21": "z21",
    "Z23 Kai": "z23_g",
    "Z23": "z23",
    "Z23_2": "z23_2",
    "Z25": "Z25",
    "Z25_2": "z25_2",
    "Z35": "z35",
    "Z46": "Z46",
    "Z46_2": "Z46_2",
    "Ztingdanchuan": "Ztingdanchuan",
    "Zuikaku": "ruihe",
    "anniupaodan": "anniupaodan",
    "bailudanchuan": "bailudanchuan",
    "biandangpaodan": "biandangpaodan",
    "bianpaojiu": "bianpaojiu",
    "biruiwudaodanchuan1": "biruiwudaodanchuan1",
    "boom": "boom",
    "boom1": "boom1",
    "boom2": "boom2",
    "boom3": "boom3",
    "caishen": "caishen",
    "changliangdanchuan": "changliangdanchuan",
    "chuanneidanchuan": "chuanneidanchuan",
    "chuixuedanchuan": "chuixuedanchuan",
    "denglong": "denglong",
    "dishu": "dishu",
    "fangkongdanchuan": "fangkongdanchuan",
    "fenbizidan": "fenbizidan",
    "fusangdanchuan": "fusangdanchuan",
    "gaoxiongdanchuan": "gaoxiongdanchuan",
    "guyingdanchuan": "guyingdanchuan",
    "haibaohongzhaji": "haibaohongzhaji",
    "haibaopaodan": "haibaopaodan",
    "haibaoyulei": "haibaoyulei",
    "haibaoyuleiji": "haibaoyuleiji",
    "heibancapaodan": "heibancapaodan",
    "huabanzidan": "huabanzidan",
    "hude Wedding": "hude_h",
    "hude": "hude",
    "hude_2": "hude_2",
    "jinbijiu": "jinbijiu",
    "jinyuanbao": "jinyuanbao",
    "juzi": "juzi",
    "lenggui": "lenggui",
    "liandedanchuan": "liandedanchuan",
    "liangjiaoqipaodan": "liangjiaoqipaodan",
    "loader": "loader",
    "mahandanchuan": "mahandanchuan",
    "manjuupengquan": "manjuupengquan",
    "mantoufeiji": "mantoufeiji",
    "mantoupaodan": "mantoupaodan",
    "mantouyulei": "mantouyulei",
    "miaogaodanchuan": "miaogaodanchuan",
    "moguiyu": "moguiyu",
    "muyuedanchuan": "muyuedanchuan",
    "nuofukedanchuan": "nuofukedanchuan",
    "paozhang": "paozhang",
    "qiantingdanchuan": "qiantingdanchuan",
    "qingyedanchuan": "qingyedanchuan",
    "qiumodanchuan": "qiumodanchuan",
    "sairenboss": "sairenboss",
    "sairenhangmu": "sairenhangmu",
    "sairenhangmu_i": "sairenhangmu_i",
    "sairenqianting": "sairenqianting",
    "sairenqingxun": "sairenqingxun",
    "sairenqingxun_i": "sairenqingxun_i",
    "sairenquzhu": "sairenquzhu",
    "sairenquzhu_i": "sairenquzhu_i",
    "sairenyulei": "sairenyulei",
    "sairenzhanlie": "sairenzhanlie",
    "sairenzhanlie_i": "sairenzhanlie_i",
    "sairenzhongxun": "sairenzhongxun",
    "sairenzhongxun_i": "sairenzhongxun_i",
    "shengdanfeijiu": "shengdanfeijiu",
    "shengdanlaojiu": "shengdanlaojiu",
    "shengdanshuyulei": "shengdanshuyulei",
    "shilaimupaodan": "shilaimupaodan",
    "shizipaodan": "shizipaodan",
    "skeleton": "skeleton",
    "srBB": "srBB",
    "srBB2": "srBB2",
    "srCA": "srCA",
    "srCA2": "srCA2",
    "srCL": "srCL",
    "srCL2": "srCL2",
    "srCV": "srCV",
    "srCV2": "srCV2",
    "srDD": "srDD",
    "srDD2": "srDD2",
    "tanxiangshan": "tanxiangshan",
    "tongban": "tongban",
    "tonghuachengbaoB": "tonghuachengbaoB",
    "unknown1": "unknown1",
    "unknown3": "unknown3",
    "weixiudanchuan": "weixiudanchuan",
    "weixiudanchuan2": "weixiudanchuan2",
    "wushilingdanchuan": "wushilingdanchuan",
    "xiangguzidan": "xiangguzidan",
    "xianyuhongzhajiJP": "xianyuhongzhajiJP",
    "xianyupaodan": "xianyupaodan",
    "xianyuyuleiJP": "xianyuyuleiJP",
    "xianyuyuleijiJP": "xianyuyuleijiJP",
    "xiyundanchuan": "xiyundanchuan",
    "yangyandanchuan": "yangyandanchuan",
    "yanhuapaodan": "yanhuapaodan",
    "yishidanchuan": "yishidanchuan",
    "yuleiting": "yuleiting",
    "yunshuchuan": "yunshuchuan",
    "zhongguojie": "zhongguojie",
    "zibaochuan": "zibaochuan",
    "zuishangdanchuan2": "zuishangdanchuan2",
    
    "fusangdanchuan_kizuna": "fusangdanchuan_kizuna",
    "miaogaodanchuan_kizuna": "miaogaodanchuan_kizuna",
    "yangyandanchuan_kizuna": "yangyandanchuan_kizuna",
    "zibao_kizuna": "zibao_kizuna",
};
